export default function DotSquare() {
    return (
        <svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
            <g clipPath="url(#clip0_43_1157)">
                <circle cx="1" cy="1" r="1" fill="#C7FFDA" />
                <circle cx="9" cy="1" r="1" fill="#C7FFDA" />
                <circle cx="17" cy="1" r="1" fill="#C7FFDA" />
                <circle cx="25" cy="1" r="1" fill="#C7FFDA" />
                <circle cx="33" cy="1" r="1" fill="#C7FFDA" />
                <circle cx="41" cy="1" r="1" fill="#C7FFDA" />
                <circle cx="49" cy="1" r="1" fill="#C7FFDA" />
                <circle cx="57" cy="1" r="1" fill="#C7FFDA" />
                <circle cx="65" cy="1" r="1" fill="#C7FFDA" />
                <circle cx="73" cy="1" r="1" fill="#C7FFDA" />
                <circle cx="81" cy="1" r="1" fill="#C7FFDA" />
                <circle cx="89" cy="1" r="1" fill="#C7FFDA" />
                <circle cx="97" cy="1" r="1" fill="#C7FFDA" />
                <circle cx="1" cy="9" r="1" fill="#C7FFDA" />
                <circle cx="9" cy="9" r="1" fill="#C7FFDA" />
                <circle cx="17" cy="9" r="1" fill="#C7FFDA" />
                <circle cx="25" cy="9" r="1" fill="#C7FFDA" />
                <circle cx="33" cy="9" r="1" fill="#C7FFDA" />
                <circle cx="41" cy="9" r="1" fill="#C7FFDA" />
                <circle cx="49" cy="9" r="1" fill="#C7FFDA" />
                <circle cx="57" cy="9" r="1" fill="#C7FFDA" />
                <circle cx="65" cy="9" r="1" fill="#C7FFDA" />
                <circle cx="73" cy="9" r="1" fill="#C7FFDA" />
                <circle cx="81" cy="9" r="1" fill="#C7FFDA" />
                <circle cx="89" cy="9" r="1" fill="#C7FFDA" />
                <circle cx="97" cy="9" r="1" fill="#C7FFDA" />
                <circle cx="1" cy="17" r="1" fill="#C7FFDA" />
                <circle cx="9" cy="17" r="1" fill="#C7FFDA" />
                <circle cx="17" cy="17" r="1" fill="#C7FFDA" />
                <circle cx="25" cy="17" r="1" fill="#C7FFDA" />
                <circle cx="33" cy="17" r="1" fill="#C7FFDA" />
                <circle cx="41" cy="17" r="1" fill="#C7FFDA" />
                <circle cx="49" cy="17" r="1" fill="#C7FFDA" />
                <circle cx="57" cy="17" r="1" fill="#C7FFDA" />
                <circle cx="65" cy="17" r="1" fill="#C7FFDA" />
                <circle cx="73" cy="17" r="1" fill="#C7FFDA" />
                <circle cx="81" cy="17" r="1" fill="#C7FFDA" />
                <circle cx="89" cy="17" r="1" fill="#C7FFDA" />
                <circle cx="97" cy="17" r="1" fill="#C7FFDA" />
                <circle cx="1" cy="25" r="1" fill="#C7FFDA" />
                <circle cx="9" cy="25" r="1" fill="#C7FFDA" />
                <circle cx="17" cy="25" r="1" fill="#C7FFDA" />
                <circle cx="25" cy="25" r="1" fill="#C7FFDA" />
                <circle cx="33" cy="25" r="1" fill="#C7FFDA" />
                <circle cx="41" cy="25" r="1" fill="#C7FFDA" />
                <circle cx="49" cy="25" r="1" fill="#C7FFDA" />
                <circle cx="57" cy="25" r="1" fill="#C7FFDA" />
                <circle cx="65" cy="25" r="1" fill="#C7FFDA" />
                <circle cx="73" cy="25" r="1" fill="#C7FFDA" />
                <circle cx="81" cy="25" r="1" fill="#C7FFDA" />
                <circle cx="89" cy="25" r="1" fill="#C7FFDA" />
                <circle cx="97" cy="25" r="1" fill="#C7FFDA" />
                <circle cx="1" cy="33" r="1" fill="#C7FFDA" />
                <circle cx="9" cy="33" r="1" fill="#C7FFDA" />
                <circle cx="17" cy="33" r="1" fill="#C7FFDA" />
                <circle cx="25" cy="33" r="1" fill="#C7FFDA" />
                <circle cx="33" cy="33" r="1" fill="#C7FFDA" />
                <circle cx="41" cy="33" r="1" fill="#C7FFDA" />
                <circle cx="49" cy="33" r="1" fill="#C7FFDA" />
                <circle cx="57" cy="33" r="1" fill="#C7FFDA" />
                <circle cx="65" cy="33" r="1" fill="#C7FFDA" />
                <circle cx="73" cy="33" r="1" fill="#C7FFDA" />
                <circle cx="81" cy="33" r="1" fill="#C7FFDA" />
                <circle cx="89" cy="33" r="1" fill="#C7FFDA" />
                <circle cx="97" cy="33" r="1" fill="#C7FFDA" />
                <circle cx="1" cy="41" r="1" fill="#C7FFDA" />
                <circle cx="9" cy="41" r="1" fill="#C7FFDA" />
                <circle cx="17" cy="41" r="1" fill="#C7FFDA" />
                <circle cx="25" cy="41" r="1" fill="#C7FFDA" />
                <circle cx="33" cy="41" r="1" fill="#C7FFDA" />
                <circle cx="41" cy="41" r="1" fill="#C7FFDA" />
                <circle cx="49" cy="41" r="1" fill="#C7FFDA" />
                <circle cx="57" cy="41" r="1" fill="#C7FFDA" />
                <circle cx="65" cy="41" r="1" fill="#C7FFDA" />
                <circle cx="73" cy="41" r="1" fill="#C7FFDA" />
                <circle cx="81" cy="41" r="1" fill="#C7FFDA" />
                <circle cx="89" cy="41" r="1" fill="#C7FFDA" />
                <circle cx="97" cy="41" r="1" fill="#C7FFDA" />
                <circle cx="1" cy="49" r="1" fill="#C7FFDA" />
                <circle cx="9" cy="49" r="1" fill="#C7FFDA" />
                <circle cx="17" cy="49" r="1" fill="#C7FFDA" />
                <circle cx="25" cy="49" r="1" fill="#C7FFDA" />
                <circle cx="33" cy="49" r="1" fill="#C7FFDA" />
                <circle cx="41" cy="49" r="1" fill="#C7FFDA" />
                <circle cx="49" cy="49" r="1" fill="#C7FFDA" />
                <circle cx="57" cy="49" r="1" fill="#C7FFDA" />
                <circle cx="65" cy="49" r="1" fill="#C7FFDA" />
                <circle cx="73" cy="49" r="1" fill="#C7FFDA" />
                <circle cx="81" cy="49" r="1" fill="#C7FFDA" />
                <circle cx="89" cy="49" r="1" fill="#C7FFDA" />
                <circle cx="97" cy="49" r="1" fill="#C7FFDA" />
                <circle cx="1" cy="57" r="1" fill="#C7FFDA" />
                <circle cx="9" cy="57" r="1" fill="#C7FFDA" />
                <circle cx="17" cy="57" r="1" fill="#C7FFDA" />
                <circle cx="25" cy="57" r="1" fill="#C7FFDA" />
                <circle cx="33" cy="57" r="1" fill="#C7FFDA" />
                <circle cx="41" cy="57" r="1" fill="#C7FFDA" />
                <circle cx="49" cy="57" r="1" fill="#C7FFDA" />
                <circle cx="57" cy="57" r="1" fill="#C7FFDA" />
                <circle cx="65" cy="57" r="1" fill="#C7FFDA" />
                <circle cx="73" cy="57" r="1" fill="#C7FFDA" />
                <circle cx="81" cy="57" r="1" fill="#C7FFDA" />
                <circle cx="89" cy="57" r="1" fill="#C7FFDA" />
                <circle cx="97" cy="57" r="1" fill="#C7FFDA" />
                <circle cx="1" cy="65" r="1" fill="#C7FFDA" />
                <circle cx="9" cy="65" r="1" fill="#C7FFDA" />
                <circle cx="17" cy="65" r="1" fill="#C7FFDA" />
                <circle cx="25" cy="65" r="1" fill="#C7FFDA" />
                <circle cx="33" cy="65" r="1" fill="#C7FFDA" />
                <circle cx="41" cy="65" r="1" fill="#C7FFDA" />
                <circle cx="49" cy="65" r="1" fill="#C7FFDA" />
                <circle cx="57" cy="65" r="1" fill="#C7FFDA" />
                <circle cx="65" cy="65" r="1" fill="#C7FFDA" />
                <circle cx="73" cy="65" r="1" fill="#C7FFDA" />
                <circle cx="81" cy="65" r="1" fill="#C7FFDA" />
                <circle cx="89" cy="65" r="1" fill="#C7FFDA" />
                <circle cx="97" cy="65" r="1" fill="#C7FFDA" />
                <circle cx="1" cy="73" r="1" fill="#C7FFDA" />
                <circle cx="9" cy="73" r="1" fill="#C7FFDA" />
                <circle cx="17" cy="73" r="1" fill="#C7FFDA" />
                <circle cx="25" cy="73" r="1" fill="#C7FFDA" />
                <circle cx="33" cy="73" r="1" fill="#C7FFDA" />
                <circle cx="41" cy="73" r="1" fill="#C7FFDA" />
                <circle cx="49" cy="73" r="1" fill="#C7FFDA" />
                <circle cx="57" cy="73" r="1" fill="#C7FFDA" />
                <circle cx="65" cy="73" r="1" fill="#C7FFDA" />
                <circle cx="73" cy="73" r="1" fill="#C7FFDA" />
                <circle cx="81" cy="73" r="1" fill="#C7FFDA" />
                <circle cx="89" cy="73" r="1" fill="#C7FFDA" />
                <circle cx="97" cy="73" r="1" fill="#C7FFDA" />
                <circle cx="1" cy="81" r="1" fill="#C7FFDA" />
                <circle cx="9" cy="81" r="1" fill="#C7FFDA" />
                <circle cx="17" cy="81" r="1" fill="#C7FFDA" />
                <circle cx="25" cy="81" r="1" fill="#C7FFDA" />
                <circle cx="33" cy="81" r="1" fill="#C7FFDA" />
                <circle cx="41" cy="81" r="1" fill="#C7FFDA" />
                <circle cx="49" cy="81" r="1" fill="#C7FFDA" />
                <circle cx="57" cy="81" r="1" fill="#C7FFDA" />
                <circle cx="65" cy="81" r="1" fill="#C7FFDA" />
                <circle cx="73" cy="81" r="1" fill="#C7FFDA" />
                <circle cx="81" cy="81" r="1" fill="#C7FFDA" />
                <circle cx="89" cy="81" r="1" fill="#C7FFDA" />
                <circle cx="97" cy="81" r="1" fill="#C7FFDA" />
                <circle cx="1" cy="89" r="1" fill="#C7FFDA" />
                <circle cx="9" cy="89" r="1" fill="#C7FFDA" />
                <circle cx="17" cy="89" r="1" fill="#C7FFDA" />
                <circle cx="25" cy="89" r="1" fill="#C7FFDA" />
                <circle cx="33" cy="89" r="1" fill="#C7FFDA" />
                <circle cx="41" cy="89" r="1" fill="#C7FFDA" />
                <circle cx="49" cy="89" r="1" fill="#C7FFDA" />
                <circle cx="57" cy="89" r="1" fill="#C7FFDA" />
                <circle cx="65" cy="89" r="1" fill="#C7FFDA" />
                <circle cx="73" cy="89" r="1" fill="#C7FFDA" />
                <circle cx="81" cy="89" r="1" fill="#C7FFDA" />
                <circle cx="89" cy="89" r="1" fill="#C7FFDA" />
                <circle cx="97" cy="89" r="1" fill="#C7FFDA" />
                <circle cx="1" cy="97" r="1" fill="#C7FFDA" />
                <circle cx="9" cy="97" r="1" fill="#C7FFDA" />
                <circle cx="17" cy="97" r="1" fill="#C7FFDA" />
                <circle cx="25" cy="97" r="1" fill="#C7FFDA" />
                <circle cx="33" cy="97" r="1" fill="#C7FFDA" />
                <circle cx="41" cy="97" r="1" fill="#C7FFDA" />
                <circle cx="49" cy="97" r="1" fill="#C7FFDA" />
                <circle cx="57" cy="97" r="1" fill="#C7FFDA" />
                <circle cx="65" cy="97" r="1" fill="#C7FFDA" />
                <circle cx="73" cy="97" r="1" fill="#C7FFDA" />
                <circle cx="81" cy="97" r="1" fill="#C7FFDA" />
                <circle cx="89" cy="97" r="1" fill="#C7FFDA" />
                <circle cx="97" cy="97" r="1" fill="#C7FFDA" />
            </g>
            <defs>
                <clipPath id="clip0_43_1157">
                    <rect width="100" height="100" fill="white" />
                </clipPath>
            </defs>
        </svg>

    )
}