import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Quantico } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Adicione os pesos necessários
});

const quantico = Quantico({
  subsets: ["latin"], // Subset básico para idiomas ocidentais
  weight: ["400", "700"], // Pesos disponíveis para Quantico
  variable: "--font-quantico", // Variável CSS para integração com Tailwind
});



export const metadata: Metadata = {
  title: "Matheus de Oliveira - Portfólio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${quantico.variable} font-poppins antialiased select-none`}
      >
        {children}
      </body>
    </html>
  );
}